#!/usr/bin/env python3
"""Rebuild the Card Samples dashboard, and export a sanitised copy.

Every faceplate in the catalogue gets a card, bound to whatever live
entities fill the roles it names, so the dashboard is a real test of the
build rather than a mock-up. Views are grouped by card.

The exported `samples/dashboard.yaml` is published, so it is sanitised
hard: every entity id is replaced by a neutral one named after the role
it fills, and every strip label by its index. Nothing from this estate
reaches the repository.

    python3 scripts/build-samples.py [--no-export]
"""
import asyncio
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ha_ws import connect  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
CATALOGUE = REPO / "faceplates" / "index.json"
EXPORT = REPO / "samples" / "dashboard.yaml"
URL_PATH = "card-samples"

# Which view a card's samples land in.
VIEWS = {
    "bms-meter-card": ("Meters", "mdi:gauge"),
    "hvac-controller-card": ("Controllers", "mdi:thermostat"),
    "pump-system-card": ("Plant", "mdi:pump"),
    "plant-equipment-card": ("Fans & Plant", "mdi:fan"),
    "audio-zone-card": ("Audio", "mdi:speaker"),
    "room-controller-card": ("Rooms", "mdi:television-classic"),
    "fire-panel-card": ("Fire", "mdi:fire-alert"),
}

ABOUT = (
    "## Card samples\n\n"
    "Every faceplate in the catalogue, bound to live points where this "
    "site has them. Generated by `scripts/build-samples.py` — edits here "
    "are overwritten.\n\n"
    "Brand names identify the hardware a faceplate emulates. Those marks "
    "belong to their respective owners; these cards are independent and "
    "unaffiliated."
)


def role_pool(states: dict) -> dict:
    """Pick one live entity per role, by the patterns the cards use.

    Deliberately pattern-based rather than a hand-written map: a new
    faceplate then binds itself, and nothing site-specific is written
    down here.
    """
    patterns = {
        "energy_total": r"metertotal$|_energy_total$",
        "power_total": r"3phase_active_power$|_active_power$",
        "power_l1": r"active_power_p1$", "power_l2": r"active_power_p2$",
        "power_l3": r"active_power_p3$",
        "volts_l1": r"phase_1_v$", "volts_l2": r"phase_2_v$",
        "volts_l3": r"phase_3_v$",
        "current_l1": r"phase_1_a$", "current_l2": r"phase_2_a$",
        "current_l3": r"phase_3_a$",
        "power_factor": r"power_factor$", "frequency": r"_frequency$",
        "volume_total": r"_cubicmetre$",
        "room_temp": r"_room_temp$|_roomtemp$",
        "setpoint": r"_setpoint$|_set_temp$",
        "hvac_mode": r"_mode$",
        "system_pressure": r"_current_pressure$",
        "pressure_setpoint": r"_set_pressure$",
        "common_fault": r"_system_fault_history$",
        "flow_temp": r"_flow_temp$", "return_temp": r"_return_temp$",
    }
    for n in (1, 2, 3):
        patterns[f"pump{n}_speed"] = rf"_pump_{n}_inverter_output_hz$"
        patterns[f"pump{n}_current"] = rf"_pump_{n}_inverter_output_a$"
        patterns[f"pump{n}_run"] = rf"_pump_{n}_run$"

    pool = {}
    for role, pattern in patterns.items():
        hit = next((e for e in sorted(states) if re.search(pattern, e)), None)
        if hit:
            pool[role] = hit

    # Audio zones: a number/switch pair per zone, in entity-id order.
    index = 0
    for entity in sorted(states):
        match = re.match(r"number\.(.+)_volume$", entity)
        if not match or f"switch.{match.group(1)}_mute" not in states:
            continue
        index += 1
        if index > 4:
            break
        pool[f"zone{index}_volume"] = entity
        pool[f"zone{index}_mute"] = f"switch.{match.group(1)}_mute"
    return pool


def sanitise(node, counter):
    """Strip the estate out of the published copy."""
    if isinstance(node, dict):
        out = {}
        for key, value in node.items():
            if key == "entities" and isinstance(value, dict):
                out[key] = {
                    role: f"{'switch' if role.endswith('mute') else 'sensor'}.{role}"
                    for role in value
                }
            elif key == "labels" and isinstance(value, dict):
                out[key] = {k: f"Zone {i}" for i, k in enumerate(value, start=1)}
            else:
                out[key] = sanitise(value, counter)
        return out
    if isinstance(node, list):
        return [sanitise(item, counter) for item in node]
    return node


async def main() -> None:
    catalogue = json.loads(CATALOGUE.read_text())["faceplates"]

    async with connect() as ha:
        states = {s["entity_id"]: s for s in await ha.cmd("get_states")}
        pool = role_pool(states)

        views = [{
            "title": "About", "path": "about", "icon": "mdi:information-outline",
            "cards": [{"type": "markdown", "content": ABOUT}],
        }]

        by_card: dict[str, list] = {}
        for face in catalogue:
            by_card.setdefault(face["card"], []).append(face)

        for card, faces in sorted(by_card.items()):
            title, icon = VIEWS.get(card, (card, "mdi:card-outline"))
            cards = []
            for face in sorted(faces, key=lambda f: f["name"]):
                note = f"### {face['name']}\n`faceplate: {face['id']}`"
                if face.get("emulates"):
                    note += f"  \nEmulates {face['emulates']}."
                cards.append({"type": "markdown", "content": note})

                config = {
                    "type": f"custom:{card}",
                    "faceplate": face["id"],
                    "title": face["name"],
                    "entities": {
                        role: pool[role] for role in face["roles"] if role in pool
                    },
                }
                if face.get("options"):
                    config["options"] = {
                        o["key"]: o["default"] for o in face["options"]
                    }
                cards.append(config)
            views.append({
                "title": title, "path": card, "icon": icon,
                "cards": [{"type": "grid", "columns": 2, "square": False,
                           "cards": cards}],
            })

        config = {"views": views}

        existing = await ha.cmd("lovelace/dashboards/list")
        if not any(d["url_path"] == URL_PATH for d in existing):
            await ha.cmd("lovelace/dashboards/create", url_path=URL_PATH,
                         title="Card Samples", mode="storage",
                         icon="mdi:card-multiple", show_in_sidebar=True)
        await ha.cmd("lovelace/config/save", url_path=URL_PATH, config=config)
        total = sum(1 for v in views for c in v["cards"]
                    for cc in c.get("cards", []) if str(cc.get("type", "")).startswith("custom:"))
        print(f"saved {total} samples across {len(views)} views")

    if "--no-export" in sys.argv:
        return
    import yaml
    EXPORT.parent.mkdir(parents=True, exist_ok=True)
    EXPORT.write_text(yaml.safe_dump(sanitise(config, {}), sort_keys=False,
                                     default_flow_style=False, width=88))
    print(f"exported {EXPORT.relative_to(REPO)} (sanitised)")


asyncio.run(main())
